### ISSUE TITLE
'make install' fails with 'Failed to load I18N.dll'

### ISSUE THREAD

**Issue by huybui02** [mrts/git-svn-bridge#1] opened 2017-09-21 03:44 UTC
Here error:
![yerror](https://user-images.githubusercontent.com/28868748/30678046-bcb2b594-9eb9-11e7-8c8b-14f3b953fe0c.png)

**Comment by mrts** [comment] 2017-09-21 11:23
What's the Ubuntu version you are using? Did you follow the advice [to use latest Mono in synchronization utilities section](https://github.com/mrts/git-svn-bridge#synchronization-utilities):

> The versions of Mono and Git provided in Ubuntu 16.04 cause problems as described below, please use [latest Mono](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) and Git if you run into problems.

It looks like your Mono installation is a bit messed up, but I may be wrong.

**Comment by huybui02** [comment] 2017-09-25 10:17
Disturb you, my skill English is very bad.  
Exactly right, I use ubuntu on Vitualbox. And my Mono have mamy error.
I try re-intall mono on [](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives), but it through error : 

`W: GPG error: http://mono-project.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY <Key>`

Thanks!

**Comment by mrts** [comment] 2017-09-26 07:57
See instructions here: http://www.mono-project.com/download/#download-lin

You need to run the following command to import the GPG key

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
```

I'll close the issue as the problem is not caused by `git-svn-bridge` code.

**Closed as completed** 2017-09-26 07:58 UTC
Labels: invalid
